Feature/today
DeveloperAcademy-POSTECH/MC3-Team7-MoTe pull request #11
Opened 2022-07-15 05:27 UTC by wody-d

## 이슈번호 
#8 

## 작업사항

스케치에 올라온 화면대로 개발하였습니다. 설정 버튼은 네비게이션바의 rightItem으로 구성하였습니다. 아보의 dynamic을 고려한 디자인 의도대로 iOS 텍스트 스타일을 그대로 적용하였고, 이미지에도 텍스트 스타일을 적용하였습니다. (해당 레퍼런스는 이슈 댓글에 달려있습니다.) 

디자인 수정사항이 생긴다면 이슈 새로 생성 후 반영하겠습니다.

## 스크린샷

| 작업 전 | 작업 후 |
| ----- | ----- | 
| <img src="https://user-images.githubusercontent.com/56102421/179156184-a46a0e8b-a067-4c17-957a-d870a8c9ebce.png" width="250"> | <img src="https://user-images.githubusercontent.com/56102421/179156192-dd492bec-fd47-4e9d-9b4f-38ae8fbca12e.png" width="250"> |

## 검토할 사항
- [ ] 주석 제거
- [ ] 피드백 반영

2022-07-15 08:03 UTC, Chaeho-Min requested changes
addSubView와 addArrangedSubView를 익스텐션을 통해 쉽게 추가할 수 있군요! 하나 배워갑니다.

기록하기 버튼의 크기가 상황에 따라 변할 수 있도록 수정사항 적용 부탁드립니다.

2022-07-15 08:03 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/TodayViewController.swift
> +        $0.configuration?.cornerStyle = .medium
p2;

Dynamics Type이 적용되어 버튼 글자 크기가 달라지거나, 추후에 라이팅 수정으로 인해 버튼 문구가 달라질 수 있으므로 확장성을 위해 여기서 글자에 패딩값을 주어 버튼 크기가 변할 수 있도록 해주세요.

패딩값은 추후 디자인이 수정될 수 있으니 일단 아무값이나 넣으셔도 됩니다.
```suggestion
        $0.configuration?.cornerStyle = .medium
        $0.configuration?.contentInsets = NSDirectionalEdgeInsets.init(top: 16, leading: 16, bottom: 16, trailing: 16)
```

2022-07-15 08:15 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/TodayViewController.swift
> +        $0.configuration?.cornerStyle = .medium
원래 제가 의도한건 버튼도 라운드값을 15로 주는거였는데, 여기서 적용한 .medium과 비교해보니까 .medium이 더 괜찮아보이네요. 초기설정 화면에서 나오는 버튼들도 medium 속성을 적용해주는걸 고려해봐야겠습니다.

2022-07-15 08:19 UTC, deslog reviewed
addsubView extension으로 빼놓고 저렇게 간편하게 만드신거 감탄하고 갑니다...🌳🌳

2022-07-15 08:19 UTC, deslog commented on Alarmi/Alarmi/Sources/ViewControllers/TodayViewController.swift
> +        ])
p1;

(p1이자 그냥 코멘트...) 동의하빈다! 코드를 보면서 저는 단순히 105를 임의로 주면 안되지 않을까? 생각했는데, 아보가 정확한 솔루션을 내주셨네요👍 ㅠㅠ 많이 배워갑니다. 참고하시기 좋게 스크린샷 첨부합니다.

|변경 전 (105임의로 줬을 경우)|변경 후(가운데정렬로 구속)|
|---|---|
|<img width="200" alt="image" src="https://user-images.githubusercontent.com/96969693/179182372-e562d6f5-2dcc-4150-83a4-9785d8a4c802.png">|<img width="200" alt="image" src="https://user-images.githubusercontent.com/96969693/179182239-3ef349bb-f5d8-42d0-b635-0c443fa83215.png">|

2022-07-15 08:25 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/TodayViewController.swift
> +        $0.font = UIFont.preferredFont(forTextStyle: .title2)
p1;

이렇게만 지정해주면 dynamic types 적용이 안됩니다.
UILabel들에 모두 속성 두 가지 더 붙여주세요.
```suggestion
        $0.font = UIFont.preferredFont(forTextStyle: .title2)
        $0.adjustsFontForContentSizeCategory = true
        $0.numberOfLines = 0
```

dynamic types의 길은 너무 험하네요ㅠㅠ 너무 욕심이었을까요?

2022-07-15 11:19 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/TodayViewController.swift
> +        $0.configuration?.attributedTitle = AttributedString("오늘 전화 기록하기 ", attributes: container)
"오늘 전화 기록하기 " 끝에 있는 공백 지워주세요.

```suggestion
        $0.configuration?.attributedTitle = AttributedString("오늘 전화 기록하기", attributes: container)
```

2022-07-15 11:23 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/TodayViewController.swift
> +        $0.configuration?.attributedTitle = AttributedString("이번 연락 미루기", attributes: container)
p1;

"이번 연락 미루기" 끝에 공백 추가해주세요.

```suggestion
        $0.configuration?.attributedTitle = AttributedString("이번 연락 미루기 ", attributes: container)
```

2022-07-15 13:57 UTC, Lim-YongKwan commented on Alarmi/Alarmi/Sources/ViewControllers/TodayViewController.swift
> +        let config = UIImage.SymbolConfiguration(font: UIFont.preferredFont(forTextStyle: .caption2))
제가 아직 코드를 잘 이해하지 못해서 하는 질문인데

` let config = UIImage.SymbolConfiguration(font: UIFont.preferredFont(forTextStyle: .caption2))`

에서 뒤의 부분의 Font가 잘 이해가 안 됩니다.
밑에서 이번 연락 미루기는 font인게 확실히 이해가 되는데 해당 부분에서는 왜 Font가 쓰이는지 혹시 알 수 있을까요...?

2022-07-15 13:57 UTC, Lim-YongKwan commented on Alarmi/Alarmi/Sources/ViewControllers/TodayViewController.swift
> +        ])
아보 의견에 동의하면서 동시에 가지는 의문입니다.
저도 상수값을 주는것보다는 다른 방식을 해야 한다고 생각하는데 버튼 크기를 안에 있는 글자 크기에 맞추는 방법은 없을까요?
아니면 혹은 Label로 글자를 띄운 뒤에 버튼을 뒤에 두고 앞에 있는 Label의 크기에 맞춘다는 방식은 없는지 궁금합니다!

2022-07-15 13:58 UTC, Lim-YongKwan approved these changes

2022-07-15 14:14 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/TodayViewController.swift
> +        $0.configuration?.cornerStyle = .medium
아, 사실 이 부분에 대해서 아까 이야기했어야 했었는데 깜박했네요. 

제가 이번에 버튼을 만든 방식은 iOS13이상부터 지원하는 API인 `Button.Configuration`을 사용했습니다. cornerRadius를 주는 방식도 [이 링크](https://developer.apple.com/documentation/uikit/uibutton/configuration/cornerstyle)를 보시면 small, medium, large, capsule 4가지 고정된 타입이 있고, 직접 설정도 할 수 있습니다. 그래서 직접 설정하는 것보다 이 값을 이용하면 더욱 통일된 UI를 구성할 수 있을 것 같아 제안하려고 했습니다.

2022-07-15 14:16 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/TodayViewController.swift
> +        $0.configuration?.cornerStyle = .medium
확인했습니다.

2022-07-15 14:26 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/TodayViewController.swift
> +        ])
어 이부분은 아직 디자인이 완료가 되지 않았기 때문에 스케치에 디자인된 하이파이 그대로 작성하였습니다. 아까 아보가 **오늘 전화기록하기** 버튼은 디자인중이라구 했기때문입니다. 일단 아보 의견대로 버튼의 패딩값을 16을 주었고 양 사이드는 최소 마진 16으로 constraint를 주었습니다.  

그리고 `UIScreen.main`이 deprecated가 된다는 사실은 알고 있었지만 아직 대체할만한 것을 찾지 못해 계속 사용중이었습니다.. 일단 찾을 때까지 최대한 버티려고 합니다. 계속 찾아보겠습니다.

2022-07-15 14:33 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/TodayViewController.swift
> +        $0.configuration?.attributedTitle = AttributedString("이번 연락 미루기", attributes: container)
adjustsFontForContentSizeCategory 에 반영헀습니다 : )

2022-07-15 14:41 UTC, wody-d commented
승인 없이 머지되는 이유는 제가 `feature/tab` 브랜치에서 따서 다시 `feature/tab`에 머지 PR을 날렸기 때문입니다. `feature/tab`은 브랜치 룰을 설정을 안해놓아서요. 제가 카톡으로 리베이스 머지를 지양하자고 한 이유 중 하나가 여기에도 있는데, `feature/tab` 브랜치를 리베이스할 경우, 새로 딴 `feature/today`브랜치에 `feature/tab` 브랜치의 커밋들이 합쳐져서 구분이 안가기 때문에 일단 머지 커밋을 날리자는 의견이었습니다.

2022-07-15 14:51 UTC, Chaeho-Min requested changes
addArrangedSubView가 사라지고 MainTabBarController, RecordViewController가 구버전으로 변경된 치명적인 문제가 발생했습니다! 수정이 필요합니다.

2022-07-15 14:51 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/TodayViewController.swift
> -        stackView.addArrangedSubviews(descriptionLabel, subDescriptionLabel, delayButton)
p1;

얘가 갑자기 사라져서 뷰에 나타나지 않습니다!

2022-07-15 14:51 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/MainTabBarController.swift
>  class MainTabBarController: UITabBarController {
p1;

MainTabBarController와 RecordViewController가 현재 구버전인것 같습니다!
저번 PR에서 변경된 사항들이 다시 예전으로 돌아가져있네요.

2022-07-15 14:51 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/TodayViewController.swift
> +        $0.adjustsFontSizeToFitWidth = true
p3;

자동완성 잘못 누르신 것 같...
```suggestion
        $0.adjustsFontForContentSizeCategory = true
        $0.numberOfLines = 0
```
numberOfLines도 추가해야 합니다!

2022-07-15 14:51 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/TodayViewController.swift
> +        $0.adjustsFontSizeToFitWidth = true
여기도요

2022-07-15 15:35 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/TodayViewController.swift
> +        $0.adjustsFontSizeToFitWidth = true
37c3cf39384d81ed73ef24dad451514490b2d67f 반영했습니다

2022-07-15 15:35 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/TodayViewController.swift
> +        $0.adjustsFontSizeToFitWidth = true
37c3cf39384d81ed73ef24dad451514490b2d67f 반영했습니다

2022-07-15 15:36 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/MainTabBarController.swift
>  class MainTabBarController: UITabBarController {
37c3cf39384d81ed73ef24dad451514490b2d67f 반영했습니다. 리베이스하다가 잘못 합친 것 같습니다.

2022-07-15 15:36 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/TodayViewController.swift
> -        stackView.addArrangedSubviews(descriptionLabel, subDescriptionLabel, delayButton)
37c3cf39384d81ed73ef24dad451514490b2d67f 반영했습니다. 밤이라 정신없이 개발했나봅니다. 🍺🍻

2022-07-15 15:37 UTC, wody-d commented
수정했습니다. 신경 써서 커밋 못 한 점 죄송합니다. 😅

2022-07-16 00:47 UTC, Chaeho-Min approved these changes
요구사항 반영해주셔서 정말 감사합니다🙇🙇‍♀️

2022-07-16 00:47 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/Global/Extensions/UILabel+.swift
> +}
🙇👍

2022-07-16 02:31 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/TodayViewController.swift
>  class TodayViewController: UIViewController {
p3;

코딩 컨벤션에 따라 더 이상 상속이 발생하지 않는 클래스는 `final`로 선언해주세요.

2022-07-16 02:36 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/TodayViewController.swift
>  class TodayViewController: UIViewController {
c364ffe2195b8618322b5e9bd47254c7df0e2da2 반영했어요

2022-07-16 02:36 UTC, wody-d commented on Alarmi/Alarmi/Sources/Global/Extensions/UILabel+.swift
> +}
c364ffe2195b8618322b5e9bd47254c7df0e2da2 반영했어요

2022-07-16 02:36 UTC, merged