[D0] 통화 가능 시간 설정 뷰 변경
DeveloperAcademy-POSTECH/MC3-Team7-MoTe pull request #113
Opened 2022-07-31 19:15 UTC by wonny1012

## 이슈번호 
#112

## 작업사항
- 통화 가능 시간 설정 뷰 변경

## 스크린샷
<img width="150" alt="image" src="https://user-images.githubusercontent.com/102846055/182041348-1701398b-4920-4025-bef0-699552069e4d.png">  <img width="150" alt="image" src="https://user-images.githubusercontent.com/102846055/182041455-9a5ed20c-1ee2-4bcc-9d40-adb5595f743e.png">

##추가로 해야 하는 상황
- View 라운드 주는거 설정하는게 제 눈에 안보여요 ㅜㅜ
- 아디자이너님 그림에 따르면 작은 화면은 메인 화면 모드 설정과 반대되게 설정 하기 

## 검토할 사항
- Picker는 10분 단위인데 처음 보여지는 시간은 1분단위 입니다. "hh:mm"에서 m을 만지면 될꺼같은데.. 혹쉬.. 아시는분...?
- 작은 폰 뷰는 우선 보이기 쉽게 색을 입혀 놓은거라 추후 화면모드 변경 하면 바뀔 예정입니다. 
- MVVM맞게 작성한건지 모르겠어😥

+ 절리 화면 아직 수정 안된거면 뷰 만든 부분 스토리보드 같이 맞추는게 좋을듯 합니다!!

2022-08-01 06:06 UTC, Chaeho-Min requested changes
시간 연동까지 바로 해주셨군요👍
색상은 제가 나중에 일괄적으로 적용할 부분이라 신경쓰지 않으셔도 됩니다.
DateFormatter와 MVVM 관련한 코멘트를 남겨놨으니 참고바랍니다!

2022-08-01 06:06 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/Register/RegisterCallTimeViewController.swift
> +        startTimeViewLabel.text = "\(startTimeFormatter.string(from:Date()))"
p2;

기기의 시간대를 사용한다면, DateFormatter를 다시 생성해줄 필요 없이 우디가 만든 Date 익스텐션을 이용하면 됩니다.
`DateManager` 파일에 싱글톤으로 DateFormatter가 생성되어 있고, Date 익스텐션에서 이를 이용하여 "hh:mm"이나 "HH:mm"으로 변환해줍니다.
[Date 코드 개선 PR](https://github.com/DeveloperAcademy-POSTECH/MC3-Team7-MoTe/pull/107)을 참고하세요.
```swift
private func attribute() {
    startTimeViewLabel.text = Date().date2TimeString(Date(), type: ._12HTime)
    configureNavigationBar()
    configureBackground()
}
```

2022-08-01 06:06 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/Register/RegisterCallTimeViewController.swift
> +        startTimeViewLabel.text = startTimeFormatter.string(from: sender.date)
p2;

여기도 마찬가지로 Date 익스텐션을 이용하여 구현할 수 있습니다.
참고로 뷰모델에 맞으려면, 이 로직 또한 `viewModel.startTimePickerAction`에 들어가 있어야 할 것 같습니다.

2022-08-01 11:48 UTC, wonny1012 commented on Alarmi/Alarmi/Sources/Register/RegisterCallTimeViewController.swift
> +        startTimeViewLabel.text = "\(startTimeFormatter.string(from:Date()))"
수정 했습니다! (with 우디)

2022-08-01 11:49 UTC, wonny1012 commented on Alarmi/Alarmi/Sources/Register/RegisterCallTimeViewController.swift
> +        startTimeViewLabel.text = startTimeFormatter.string(from: sender.date)
수정했습니다. 근데.. 우선은 위치는 변경하지 않았어요.. 위에꺼도 그대로 둬서 일단은...

2022-08-01 11:58 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/Register/RegisterCallTimeViewController.swift
> +    let startTimeFormatter = DateFormatter()
p1;

startTimeFormatter가 이제 남아있을 필요가 없는 것 같습니다!

2022-08-01 11:58 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/Register/RegisterCallTimeViewController.swift
> +        startTimeViewLabel.text = "\(Date().date2TimeString(type: ._24HTime))"
p4;

저희 컨벤션에 따라 viewDidLoad에는 함수만 남겨두고 이건 attribute 쪽으로 옮기는건 어떤가요?

2022-08-02 01:14 UTC, Chaeho-Min approved these changes

2022-08-02 01:18 UTC, merged