[D-2] 초기 설정 완료 온보딩 화면 구현
DeveloperAcademy-POSTECH/MC3-Team7-MoTe pull request #16
Opened 2022-07-16 05:45 UTC by Chaeho-Min

## 이슈번호 
- #12 

## 작업사항
- 초기 설정 완료시 나오는 온보딩 화면을 구현했습니다.
- SwiftUI 프리뷰를 적용하기 위한 UIViewController extension을 추가했습니다.
- SwiftUI 프리뷰 구조체 이름에 언더바(_)가 들어갔을 때 빌드가 안되는 것을 없애기 위해 SwiftLint 파일을 수정했습니다.(type_name 규칙 비활성화)

## 스크린샷

| 작업 화면 | Dynamic Types 확인 |
|:---:|:---:|
|<img width="250" src="https://user-images.githubusercontent.com/75792767/179341453-8df57dc4-98b0-4a32-b773-4fa696e010cb.png">|<img width="250" alt="image" src="https://user-images.githubusercontent.com/75792767/179341700-d04c01da-2266-4729-9895-882bb6161a75.png">|

## 검토할 사항
- [ ] 빌드를 위해 SceneDelegate 수정한 것 PR로 올리지 않았는지 확인
- [ ] 필요없는 주석 제거 확인
- [ ] 컨벤션 지켰는지 확인
- [ ] final, private 제대로 넣었는지 확인
- [ ] develop에 머지하는지 확인

2022-07-16 07:14 UTC, wody-d requested changes
정말 빠르게 개발하셨네요! 수고하셨습니다:)
view의 배경색을 바꾸는 코드위치만 수정해주세요. 이 부분도 계속 재사용이 될 코드로 상속을 통해 제거해줄 수 있을 것 같은데 고민해보겠습니다.

코드 한 줄이 99자를 넘으면 안 된다는 컨벤션은 아보의 의견에 동의합니다. 레이아웃을 짜는 코드는 가시성이 좋게 작성하는 것이 1순위인 것 같기 떄문에 저는 99자를 조금 넘는 것은 개행을 하지 않았습니다. 레이아웃을 짜는 코드에선 한 줄 99자 컨벤션을 유연하게 가져갑시다.

시작 버튼도 컴포넌트화하면 좋을 것 같습니다. 이는 일단 대충 구현한 후, 모든 화면에 sync를 맞추겠습니다. 미로보드에 태스크가 이후로 나뉘어져 있어서 제가 따로 하진 않았는데 제가 이 태스크를 가져가서 하도록 하겠습니다.

2022-07-16 07:14 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/SettingCompleteViewController.swift
> +        startButton.addAction(action, for: .touchUpInside)
P3
버튼이 탭될 때 액션을 새로운 APi를 사용하셔서 구현하셨군요!
아래와 같이 버튼을 초기화할 때 함께 초기화해줄 수 있을 것 같습니다.

```swift
private lazy var startButton: UIButton = {
    $0.translatesAutoresizingMaskIntoConstraints = false
    $0.configuration?.baseBackgroundColor = .systemBlue
    $0.configuration?.titleAlignment = .center
    $0.configuration?.cornerStyle = .medium
    $0.configuration?.title = "시작"
    $0.addAction(startButtonAction, for: .touchUpInside)
    return $0
}(UIButton(configuration: .filled()))

private let startButtonAction = UIAction { _ in

}
```

2022-07-16 07:15 UTC, wody-d commented
아니, 근데 xcode14 개편하네요...? 업데이트해야하나.

2022-07-16 07:19 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/SettingCompleteViewController.swift
> +        startButton.addAction(action, for: .touchUpInside)
와 항상 초기화에 같이 넣고 싶었는데 이니셜라이저에 인스턴스 메서드나 내비게이션 푸쉬팝 못 쓴다는 오류가 나서 어쩔 수 없이 빼놨었는데 `lazy var`로 선언하면 되는군요!
`lazy var`가 뭔지 공부 해봐야겠습니다 감사합니다!

2022-07-16 07:25 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/SettingCompleteViewController.swift
> +        startButton.addAction(action, for: .touchUpInside)
푸쉬팝 예시코드가 있을까요?

2022-07-16 07:29 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/SettingCompleteViewController.swift
> +        startButton.addAction(action, for: .touchUpInside)
```swift
    private let startButton: UIButton = {
        $0.translatesAutoresizingMaskIntoConstraints = false
        $0.configuration?.baseBackgroundColor = .systemBlue
        $0.configuration?.titleAlignment = .center
        $0.configuration?.cornerStyle = .medium
        $0.configuration?.title = "시작"
        let action = UIAction { _ in
            self.navigationController?.pushViewController(MainTabBarController(), animated: true)
        }
        $0.addAction(action, for: .touchUpInside)
        return $0
    }(UIButton(configuration: .filled()))
```

또는

```swift
    private lazy var startButton: UIButton = {
        $0.translatesAutoresizingMaskIntoConstraints = false
        $0.configuration?.baseBackgroundColor = .systemBlue
        $0.configuration?.titleAlignment = .center
        $0.configuration?.cornerStyle = .medium
        $0.configuration?.title = "시작"
        $0.addAction(action, for: .touchUpInside)
        return $0
    }(UIButton(configuration: .filled()))

    private let action = UIAction { _ in
        self.navigationController?.pushViewController(MainTabBarController(), animated: true)
    }
```

Cannot use instance member 'self' within property initializer; property initializers run before 'self' is available 오류가 뜹니다.

2022-07-16 07:35 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/SettingCompleteViewController.swift
> +        startButton.addAction(action, for: .touchUpInside)
이렇게 바꿔주시면 될 거예요. 

```swift
    private lazy var action = UIAction { _ in
        self.navigationController?.pushViewController(MainTabBarController(), animated: true)
    }
```

참고로, 탭으로 전환되는 코드는 네비게이션에 쌓이는 것이 아닌 window의 rootViewController를 바꿔주세요!

2022-07-16 07:38 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/SettingCompleteViewController.swift
> +        startButton.addAction(action, for: .touchUpInside)
이유를 간단히 설명하자면, lazy 키워드를 붙여준 프로퍼티들은 init()이 실행된 후에 초기화가 됩니다. init() 이후 사용되는 시점에 초기화되는데, 클래스 생성 시 초기화 시점에 대해 더 찾아보시면 좋을 것 같아요 :)

2022-07-16 07:43 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/SettingCompleteViewController.swift
> +        startButton.addAction(action, for: .touchUpInside)
감사합니다!
8eaa24a 에 반영했습니다.

2022-07-16 07:44 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/SettingCompleteViewController.swift
> +        view.backgroundColor = .systemGroupedBackground
8eaa24a 에 반영했습니다.

2022-07-16 07:47 UTC, wody-d approved these changes
🚀

2022-07-17 03:03 UTC, deslog approved these changes
제 생각엔 리뷰할게 없는 코드입네다....! approve 드립니다 ^____^ 👀

아 그리고 개인적으로 // MARK: 로 코드의 어느 부분인지 전부 다 표시해둔게 (초보자입장에서)너무너무 읽기 편했어요! 저도 다 구분해서 //MARK: 를 달아놔야겠네요.
이렇게 다 달아놔도 너무 //MARK: 를 남발하는건 아니겟죠..?

2022-07-17 03:08 UTC, deslog approved these changes
리뷰.. 보다는 질문입니다!

2022-07-17 03:08 UTC, deslog commented on Alarmi/Alarmi/Sources/ViewControllers/SettingCompleteViewController.swift
> +    private let descriptionStack: UIStackView = {
(질문)
여기서 stack view, label들은 전부 ```let```으로 선언했고. button은 ```lazy var```로 선언했는데요.
저는 특별한 경우가 없으면 lazy var 를 사용해서 실행되기 전까지 초기값이 계산되지 않게끔 해주는게 좋다고 생각했습니다. 그래서 궁금합니다  왜 어떤경우에는 ```let```으로 선언했고 버튼같은경우에는 ```lazy var```로 선언한 이유가요.

2022-07-17 05:08 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/SettingCompleteViewController.swift
> +    private let descriptionStack: UIStackView = {
제 코드에서 let과 lazy var가 섞여있는 이유는... 제가 lazy에 대해 몰랐기 때문입니다.
그래서 전부 let으로 선언하다가 위에 있는 리뷰에서 버튼 초기화에서 인스턴스 메서드를 사용하려면 lazy를 사용해야 된다길래 버튼에만 붙은 것입니다.

브라운의 의견은 lazy에 대해 공부해보면서 한 번 생각해봐야겠네요.
아니면 저는 이거에 대한 저희의 CTO @wody-d 의 의견이 궁금합니다!

2022-07-17 05:17 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/SettingCompleteViewController.swift
> +    private let descriptionStack: UIStackView = {
제가 lazy랑 let으로 뷰를 선언하는 것의 차이를 찾다가 발견한 [링크](https://stackoverflow.com/questions/47367454/swift-lazy-var-vs-let-when-creating-views-programmatically-saving-memory)입니다.

<img width="915" alt="image" src="https://user-images.githubusercontent.com/75792767/179384926-64b6359c-969d-4fa5-8b1e-2cba8b43f2ba.png">

대충 어차피 화면에 항상 드러나는 것은 lazy로 선언해봤자 큰 의미가 없다는 뜻인 것 같네요.
특히 lazy는 스레드 안정성이 떨어진다는 단점도 갖고 있어서 필요하지 않을 때에도 lazy로 선언하는 것은 좋지 않아보입니다.

2022-07-17 16:35 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/SettingCompleteViewController.swift
> +    private let descriptionStack: UIStackView = {
위 아보의 아티클이 맞는 의견입니다. 
제 기준에서 항상 화면에 보여지는 부분은 `let`으로 선언하되, 필요하지 않은 부분은 `lazy` 키워드를 씁니다. 어떤 메소드가 초기화할 때 필요한 뷰같은 경우에는 `lazy`를 쓰는 예외 케이스도 있습니다. 이렇게 작성하는 이유는 이후 코드를 읽거나 리뷰에서 왜 이렇게 작성되었는 지 이유를 알기 쉬우려고 입니다.

2022-07-18 00:37 UTC, Lim-YongKwan approved these changes
너무 보기 좋아서 따로 별 말 안하고 approve 남깁니다!

2022-07-18 00:37 UTC, Lim-YongKwan commented on Alarmi/Alarmi/Sources/Global/Extensions/UIViewController+.swift
> +        let viewController: UIViewController
변수이름이 viewController일 이유가 있을까요?
viewController라고 이름을 지으면 헷갈릴만한 요소가 많다고 생각합니다.
코드베이스 부분이라 viewController가 뭘 사용하는지 잘 몰라서 p는 안 남깁니다!

2022-07-18 00:37 UTC, Lim-YongKwan commented on Alarmi/Alarmi/Sources/ViewControllers/SettingCompleteViewController.swift
> +struct SettingCompleteViewController_Preview: PreviewProvider {
preview를 보기 위해 따로 SwiftUI를 참조하신걸까요?
너무 보기 좋은 방식이네요!
저도 다음에 참고하도록 하겠습니다!

2022-07-18 00:41 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/Global/Extensions/UIViewController+.swift
> +        let viewController: UIViewController
SwiftUI 프리뷰에 사용할 뷰컨을 담는 상수라서 viewController로 네이밍을 하였습니다.
사실 제가 작성한 코드는 아니고 이슈에 올린 [레퍼런스 링크](https://taekki-dev.tistory.com/21)의 코드를 가져온 것입니다 ㅎㅎ

2022-07-18 03:05 UTC, deslog commented on Alarmi/Alarmi/Sources/ViewControllers/SettingCompleteViewController.swift
> +    private let descriptionStack: UIStackView = {
아하, 제가 lazy에 대해서 잘 모르고 사용해서 약간 남발..하고있던게 아닌가 생각이드네요 ㅎㅎㅎ.. 많이 배워갑니다 !! 굿굿

2022-07-18 05:20 UTC, merged