[D0] 알림 화면 구성
DeveloperAcademy-POSTECH/MC3-Team7-MoTe pull request #20
Opened 2022-07-16 09:24 UTC by wody-d

## 이슈번호 
#17 

## 작업사항
- 알림 화면 구성
- 알림에 따라 다시알림 비활성화 기능 구현
- 알림에 따라 다음 버튼 비활성화 기능 구현
- 다시알림에 따라 슬라이더 비활성화 기능 구현 
- 슬라이더에 따라 텍스트 조절 기능 구현
- 버튼 컴포넌트 추가

**버튼 컴포넌트 사용법**

```swift
let button = AMButton()
button.title = "시작"

// ✅ 높이 고정된 버튼 
// 상(하) 좌우 constraint 잡아주어야함
NSLayoutConstraint.activate([
    button.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor, constant: 0),
    button.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: 16),
    button.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -16)
])
```
## 스크린샷

| 스샷                                                         | 기능 gif                                                     |
| ------------------------------------------------------------ | ------------------------------------------------------------ |
| <img src="https://user-images.githubusercontent.com/56102421/179348882-dc67078b-f7dd-4944-84f5-8796842840cb.png" width="300"> | <img src="https://user-images.githubusercontent.com/56102421/179348835-be125acc-0481-447b-8b7f-1defae30a972.gif" width="300"> |

## 검토할 사항
- [ ] 주석 제거
- [ ] 리뷰 반영

2022-07-16 14:22 UTC, Chaeho-Min requested changes
버튼 컴포넌트화 감사합니다👍
몇 가지 고려사항을 적어놨으니 반영 부탁드립니다!

|변경 전|변경 후|
|:---:|:---:|
|<img width="300" alt="image" src="https://user-images.githubusercontent.com/75792767/179358736-b1613dd6-0e56-470d-8218-521bda9348fd.png">|<img width="300" alt="image" src="https://user-images.githubusercontent.com/75792767/179358708-250455ba-8bce-49dd-81a4-fd57c5e6aa47.png">|

이건 일전에 말했던 디자인 수정사항입니다.
슬라이더를 손으로 조작하게 되면 '최대 n번 알림을 다시 받을게요' 문구가 손가락에 가려져서 불편한 이슈가 있어서, 문구를 상단으로 올리고 '횟수' 글자를 제거했습니다.
간단한 수정사항이라 새로 이슈 파지 않고 여기서 수정해도 될 것 같아서 말씀드립니다.

2022-07-16 14:22 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/SettingAlarm/SettingNotifyViewController.swift
> +            button.topAnchor.constraint(greaterThanOrEqualTo: alarmAgainSetDescriptionLabel.bottomAnchor, constant: 16),
p3;

|구속 존재|구속 X|
|:---:|:---:|
|<img width="250" src="https://user-images.githubusercontent.com/75792767/179357912-c14e4c60-5863-407e-83f7-2ef3426b20d7.png">|<img width="250" src="https://user-images.githubusercontent.com/75792767/179358033-262af649-1722-43de-a500-7e1458fcb286.png">|

이 구속 조건이 컨텐츠가 화면 밖으로 넘어가지 않게 하여 글자 크기를 키웠을 때 numberOfLines를 0으로 했음에도 불구하고 컨텐츠가 잘리게 됩니다. Dynamic types를 고려할 것이라면 이 구속 조건을 빼고 나중에 스크롤뷰를 추가하는게 맞는 것 같습니다.

```suggestion
```

2022-07-16 14:22 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/SettingAlarm/Supporting Views/AlarmAgainSetView.swift
> +        $0.text = "다시 알림"
p1;

여기도 볼드체로 변경해주세요

2022-07-16 14:22 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/SettingAlarm/Supporting Views/AlarmAgainSetView.swift
> +        $0.value = 6
p3;

minimumValue, maximumValue, value를 상수로 관리하여 위의 minLabel과 maxLabel, 그리고 아래의 sliderLabel에 적용해주면 만약에 변경사항이 생겼을 때 오류 없이 대응하기 쉬워지지 않을까요?

2022-07-16 14:22 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/SettingAlarm/Supporting Views/AlarmAgainSetView.swift
> +        backgroundColor = .systemBackground
p1;

죄송합니다... 반영해주세요🙇‍♂️

```suggestion
        backgroundColor = .secondarySystemGroupedBackground
```

2022-07-16 14:49 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/SettingAlarm/Supporting Views/AlarmAgainSetView.swift
> +        $0.setDynamicFont(.callout)
p3;

minLabel이랑 maxLabel은 dynamic font로 주면 안될 것 같아요.
고정값으로 변경해주시면 감사하겠습니다.

2022-07-16 16:11 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/SettingAlarm/SettingNotifyViewController.swift
> +            alarmSetView.heightAnchor.constraint(greaterThanOrEqualToConstant: 80)
와 이 부분 전혀 눈치 채지 못한 부분이네요. 리뷰 감사합니다.

2022-07-16 16:15 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/SettingAlarm/SettingNotifyViewController.swift
> +            button.topAnchor.constraint(greaterThanOrEqualTo: alarmAgainSetDescriptionLabel.bottomAnchor, constant: 16),
감사합니다. 아보.

2022-07-16 16:21 UTC, wody-d commented on Alarmi/Alarmi/Sources/SceneDelegate.swift
> +        window?.rootViewController = navigationController // mainTabBarController
fc656aacd2bb99594cc5272267d3aef96171c59a 에 반영했습니다 😅 감사합니다

2022-07-16 16:22 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/SettingAlarm/SettingNotifyViewController.swift
> +            self?.enableButton(isOn)
f775f3768469960a625ca59b2be0b25dc215b5ed 에 반영했습니다.

2022-07-16 16:22 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/SettingAlarm/SettingNotifyViewController.swift
> +            let opacity: Float = canBeEdit ? 1 : 0.25
좋아요 f775f3768469960a625ca59b2be0b25dc215b5ed 에 반영했습니다.

2022-07-16 16:23 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/SettingAlarm/SettingNotifyViewController.swift
> +        view.backgroundColor = .secondarySystemBackground
f775f3768469960a625ca59b2be0b25dc215b5ed 에 반영했어요. 

- 배경색 : `systemGroupedBackground`
- Cell 배경색 : `secondarySystemGroupedBackground`
좋습니다.

2022-07-16 16:27 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/SettingAlarm/Supporting Views/AlarmSetView.swift
> +        $0.text = "알림"
f775f3768469960a625ca59b2be0b25dc215b5ed 에 반영했습니다.
UILabel extension 으로 만들어두었습니다.

알림 글자체에 집중해주세요.

| 수정 전                                                         | 수정 후                                                    |
| ------------------------------------------------------------ | ------------------------------------------------------------ |
| <img src="https://user-images.githubusercontent.com/56102421/179348882-dc67078b-f7dd-4944-84f5-8796842840cb.png" width="250"> | <img src="https://user-images.githubusercontent.com/56102421/179363484-dc8b386b-8f74-4f00-a1df-61004dcb5446.png" width="250"> |

2022-07-16 16:30 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/SettingAlarm/Supporting Views/AlarmAgainSetView.swift
> +        $0.text = "다시 알림"
f775f3768469960a625ca59b2be0b25dc215b5ed 에 반영했습니다. 
글자 크기는 아래 코멘트 스크린샷을 확인해주세요. 같은 리뷰는 답변 생략하겠습니다.

2022-07-16 16:35 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/SettingAlarm/Supporting Views/AlarmAgainSetView.swift
> +        $0.value = 6
449450785ae5b6a7f6427563f2dec1bb8c4e6b17 에 반영했습니다. 관리하기 쉬워졌네요 :) 리뷰 감사합니다.

2022-07-16 16:36 UTC, wody-d commented
아보 코드 리뷰 감사합니다. 이번 리뷰에서 잠재적 오류와 이후 수정작업에서 귀찮을 뻔한 코드들을 수정할 수 있어서 정말 좋았습니다:)

2022-07-17 00:07 UTC, Chaeho-Min approved these changes
제가 진짜 귀찮게 만들었는데 다 반영해주셔서 정말 감사합니다ㅠㅠ 앞으로도 계속 귀찮은 일 많이 해주세요!😀👻

2022-07-17 03:12 UTC, deslog commented on Alarmi/Alarmi/Sources/ViewControllers/SettingAlarm/SettingNotifyViewController.swift
> +            alarmSetView.heightAnchor.constraint(greaterThanOrEqualToConstant: 80)
대박..!

2022-07-17 07:59 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/SettingAlarm/SettingNotifyViewController.swift
> +class SettingNotifyViewController: UIViewController {
더이상 상속이 일어나지 않는 클래스는 final로 선언해주세요.

2022-07-17 16:27 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/SettingAlarm/SettingNotifyViewController.swift
> +class SettingNotifyViewController: UIViewController {
6c64aba4389bbd2c19ff1a98f04b6a270434368a 반영했어요

2022-07-17 17:06 UTC, deslog approved these changes
아보와 우디의 코드리뷰를 보고 많이 배워갑니다.. 저도 모르는게 많아서 이 리뷰들을 보고 제가 습득하고 추후에 제가 적용시켜나가야할 것들이 많이 눈에 보입니다!
아직 autolayout에 대해서 잘 모르는데, 아보와 우디의 코드에서 많이 배워갑니다 ㅎㅎㅎㅎㅎㅎㅎㅎ 구속조건을 어떻게 주냐에 따라 많은것이 달라지는군요 🫢

2022-07-18 00:30 UTC, Lim-YongKwan approved these changes
너무 수고많으셨습니다!
코드 베이스라서 잘 이해가 안 되는 부분이 많은데도 불구하고 보면서 계속 도움을 얻고 있습니다!
앞으로도 수고해주시기 바랍니다!

2022-07-18 00:30 UTC, Lim-YongKwan commented on Alarmi/Alarmi/Sources/Global/Components/AMButton.swift
> +
이 부분이 한 줄이 띄어져 있어서 궁금해서 남깁니다.
class 시작한 뒤에 한 줄이 띄어져 있는게 아무래도 가독성적으로 더 보기 좋을까요?
궁금해서 남깁니다!

2022-07-18 00:30 UTC, Lim-YongKwan commented on Alarmi/Alarmi/Sources/Global/Components/AMButton.swift
> +            heightAnchor.constraint(equalToConstant: 64)
`equalToConstant: 64`를 보다가 갑자기 궁금해서 남깁니다!
이번에 레이아웃을 짜면서 SwiftUI에서의 spacer()가 많이 필요할때가 생겼는데 UiKit에서 spacer()를 따로 구현해서 extension등으로 빼둔담에 사용할 수는 없나요?

2022-07-18 00:30 UTC, Lim-YongKwan commented on Alarmi/Alarmi/Sources/Global/Extensions/UIFont+.swift
> +
여기 줄이 띄어져 있어서 궁금해서 남깁니다.
붙이셔도 충분히 가독성이 좋은 부분인데 굳이 띄우신 이유가 있을까요?

2022-07-18 00:30 UTC, Lim-YongKwan commented on Alarmi/Alarmi/Sources/Global/Extensions/UIFont+.swift
> +
여기도 마찬가지라서 남깁니다!
가독성이 좋아질려면 밑에 return 윗줄이 띄어져도 되지 않을까요? 단순한 의견이라서 p를 안 남깁니다!

2022-07-18 00:30 UTC, Lim-YongKwan commented on Alarmi/Alarmi/Sources/ViewControllers/SettingAlarm/Supporting Views/AlarmAgainSetView.swift
> +    private let vStackView: UIStackView = {
vStackView와 hStackView 내부가 너무나도 비슷해 보여서 질문 남깁니다!
코드 베이스라면 직접 코드를 짜신걸텐데 해당부분이 많이 쓰인다면 마지막의 center와 leading을 제외하고는 따로 컴포넌트화가 안될까요?
제가 잘 모르는 부분이라서 p를 안 남깁니다!

2022-07-18 00:30 UTC, Lim-YongKwan commented on Alarmi/Alarmi/Sources/ViewControllers/SettingAlarm/Supporting Views/AlarmAgainSetView.swift
> +
p4 여기 붙여주세요!

2022-07-18 03:20 UTC, wody-d commented on Alarmi/Alarmi/Sources/Global/Components/AMButton.swift
> +
단순히 가독성을 위해서 였는데 안띄워도될거같아요. 이 부분은 자율성에 맡기겠습니다.

2022-07-18 03:22 UTC, wody-d commented on Alarmi/Alarmi/Sources/Global/Components/AMButton.swift
> +            heightAnchor.constraint(equalToConstant: 64)
이 부분은 버튼의 높이를 고정시키는 코드입니다.
Spacer()를 뷰로 짜서 만들어야하는데 오토레이아웃이랑 다른 점이 무엇일까요? 스유에서는 Spacer()를 어떤 용도로 사용하셨는지 알수 있나요?

2022-07-18 03:22 UTC, wody-d commented on Alarmi/Alarmi/Sources/Global/Components/AMButton.swift
> +            heightAnchor.constraint(equalToConstant: 64)
이 부분은 버튼의 높이를 고정시키는 코드입니다.
Spacer()를 뷰로 짜서 만들어야하는데 오토레이아웃이랑 다른 점이 무엇일까요? 스유에서는 Spacer()를 어떤 용도로 사용하셨는지 알수 있나요?

2022-07-18 03:23 UTC, wody-d commented on Alarmi/Alarmi/Sources/Global/Extensions/UIFont+.swift
> +
변수와 메소드의 구분을 주기 위함입니다. 또한 메소드에서도 역할에 구분을 주기 위해 개행합니다.

2022-07-18 03:23 UTC, wody-d commented on Alarmi/Alarmi/Sources/Global/Extensions/UIFont+.swift
> +
다음번엔 그리즐리 의견도 참고해서 띄워쓰기할게요. :)

2022-07-18 03:25 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/SettingAlarm/Supporting Views/AlarmAgainSetView.swift
> +    private let vStackView: UIStackView = {
굳이 컴포넌트화를 시킬 필요성을 못 느껴서 안 합니다. 변하는 요소도 많고 stackView의 단순히 속성을 주는 것과 컴포넌트화를 시키는 것과 차이가 없어보이는데요.

2022-07-18 03:26 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/SettingAlarm/Supporting Views/AlarmAgainSetView.swift
> +
일단 빠른개발을위해 p4는 생략할게요

2022-07-18 03:26 UTC, merged