✨ 연락 미루기 UI 구성 및 화면 연결
DeveloperAcademy-POSTECH/MC3-Team7-MoTe pull request #22
Opened 2022-07-16 09:59 UTC by wody-d

## 이슈번호 

#14 

## 작업사항

- 오늘 화면과 연락미루기 화면을 연결했습니다.
- 연락미루기 화면을 구성했습니다.

## 스크린샷

| 작업 내용 |
| ----- |
|  <img src="https://user-images.githubusercontent.com/56102421/179350100-5e707daf-96b8-4ec8-9926-c65f3035fec1.png" width="250">  |

## 검토할 사항
- [ ] 주석 제거
- [ ] 리뷰 반영

2022-07-16 14:43 UTC, Chaeho-Min requested changes
저의 실수로인한 파장이 이렇게 크게...
색깔만 변경해주시면 될 것 같아요🙇🙇‍♂️

2022-07-16 14:43 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/CallDelayViewController.swift
> +        $0.backgroundColor = .systemBackground
p1;

🙇‍♂️

```suggestion
        $0.backgroundColor = .secondarySystemGroupedBackground
```

2022-07-16 14:43 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/CallDelayViewController.swift
> +        $0.backgroundColor = .systemBackground
p1;

🙇‍♂️
```suggestion
        $0.backgroundColor = .secondarySystemGroupedBackground
```

2022-07-16 14:43 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/CallDelayViewController.swift
> +        view.backgroundColor = .secondarySystemBackground
p1;

🙇‍♂️
```suggestion
        view.backgroundColor = .systemGroupedBackground
```

2022-07-16 16:43 UTC, wody-d commented
해당 리뷰 모두 caa747fb72bfc8cfc3c275b14c070426849eaca9 에 반영했습니다.
색깔을 한곳에 묶어두고 사용할 걸 그랬어요. 제 생각이 짧았습니다. ㅎㅎ 월요일에 전 화면 sync작업을 한번 해야할 것 같습니다. 

커밋 컨벤션에서 립스틱은 "UI, 디자인 수정"인데 제가 안 적어놨었군요! 추가해두겠습니다.

2022-07-16 16:43 UTC, wody-d commented
> 저의 실수로 인한 파장이 이렇게 크게... 색깔만 변경해주시면 될 것 같아요🙇🙇‍♂️
> 
> 그리고 저희 커밋 메시지 컨벤션 위키에 립스틱 이모지에 대한 내용은 없는데 저 이모지는 무슨 의미인가요?

해당 리뷰 모두 caa747fb72bfc8cfc3c275b14c070426849eaca9 에 반영했습니다.
색깔을 한곳에 묶어두고 사용할 걸 그랬어요. 제 생각이 짧았습니다. ㅎㅎ 월요일에 전 화면 sync작업을 한번 해야할 것 같습니다. 

커밋 컨벤션에서 립스틱은 "UI, 디자인 수정"인데 제가 안 적어놨었군요! 추가해두겠습니다.

2022-07-16 23:55 UTC, Chaeho-Min approved these changes
💄💄

2022-07-17 17:08 UTC, deslog approved these changes
역시 CTO... 🫢

2022-07-18 00:15 UTC, Lim-YongKwan approved these changes
수고하셨습니다!
전 가끔 private 쓰다 보면 까먹는데 하나 하나 모두 작성해두신게 너무 좋으시네요!
너무 수고 많으셨습니다!

2022-07-18 00:15 UTC, Lim-YongKwan commented on Alarmi/Alarmi/Sources/ViewControllers/CallDelayViewController.swift
> +extension CallDelayViewController {
extension이 따로 Global쪽에 빠져있는데 이렇게 파일안에 한번에 있는 이유가 궁금합니다.
혹시 여기서만 쓰일것 같아서 이렇게 만들어 둔 건가요...?

2022-07-18 03:30 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/CallDelayViewController.swift
> +extension CallDelayViewController {
하나의 VC는 하나의 파일에 두어야 가독성이 좋아서 따로 파일로 안나누었습니다. 긴 코드도 아니어서요.

2022-07-18 03:33 UTC, merged