[D-2] 설정 화면 구현
DeveloperAcademy-POSTECH/MC3-Team7-MoTe pull request #23
Opened 2022-07-16 12:42 UTC by Chaeho-Min

## 이슈번호 
- #13 

## 작업사항
- UITableView를 이용하여 설정 화면을 구현했습니다.
- 기록 초기화 버튼 클릭시 alert가 뜨도록 했습니다.
- 셀 클릭시 색상이 회색으로 변했다가 바로 다시 원래 색으로 돌아오도록 deselectRow 코드를 추가했습니다.

## 스크린샷

|작업 화면|Alert 화면|Dynamic Types 확인|
| ----- | ----- | ----- |
|<img width="250" src="https://user-images.githubusercontent.com/75792767/179355025-7e13188f-054f-4260-967a-c6132444e269.png">|<img width="250" src="https://user-images.githubusercontent.com/75792767/179355065-460304c5-272c-420a-a55f-4b17966bfd6e.png">|<img width="250" src="https://user-images.githubusercontent.com/75792767/179355159-a6ad93ae-931c-45ab-8146-a094f215641a.png">|

## 검토할 사항
- [ ] 빌드를 위해 SceneDelegate 수정한 것 PR로 올리지 않았는지 확인
- [ ] 필요없는 주석 제거 확인
- [ ] 컨벤션 지켰는지 확인
- [ ] final, private 제대로 넣었는지 확인
- [ ] develop에 머지하는지 확인

2022-07-16 17:29 UTC, wody-d requested changes
수고하셨습니다:)
tableView가 처음이라구 하셨는데 코드로 잘 구현하신 것 같습니다. 
tableView의 constraint만 수정하시고 나머지는 리뷰를 읽으며 반영해주시면 감사하겠습니다.

2022-07-16 17:29 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/SettingViewController.swift
> +        return cell
P2

오 기본 UITableViewCell을 이용해서 구현하셨네요. 
tableView를 구성할 때 보통 cell은 reuse를 하게 하는 것이 메모리 효율을 높이는 방법입니다만, 저희 화면같이 몇 개 없을 때는 상관없을 것 같습니다. 하지만 한가지 수정하고 싶은 게 있습니다. 해당 프로퍼티는 deprecated될 에정입니다.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/56102421/179364472-7073cbfc-4544-4884-a110-6fa971152aae.png">

따라서, `UIListContentConfiguration`를 이용하여 수정하는 방법이 있습니다. 다음 코드는 [여기](https://developer.apple.com/documentation/uikit/uilistcontentconfiguration)서 가져왔습니다. 하지만 이 구조체는 iOS14이상부터 지원합니다. 다른 방법으로는 cell을 만드는 방법이 있을 것 같습니다.

또한, 조건에 의해서 변하는 프로퍼티는 삼항연산자를 이용하면 if문을 사용하지 않고 작성할 수 있습니다.

```suggestion
        let cell = UITableViewCell(style: .default, reuseIdentifier: .none)

        let text: String = settingList[indexPath.row]
        let textColor: UIColor = indexPath.row == 4 ? .systemRed : .label
        let accessoryType: UITableViewCell.AccessoryType = indexPath.row == 4 ? .none : .disclosureIndicator

        var content = cell.defaultContentConfiguration()
        content.text = text
        content.textProperties.numberOfLines = 0
        content.textProperties.color = textColor

        cell.contentConfiguration = content
        cell.accessoryType = accessoryType

        return cell
```

2022-07-16 17:29 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/SettingViewController.swift
> +        settingTableView.delegate = self
P1

이것도 마찬가지로 tableView를 생성할 때 초기화해줄 수 있습니다. tableView를 `lazy` 키워드로 바꿔주시고 코드를 옮겨주세요.

2022-07-16 17:29 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/SettingViewController.swift
> +        self.navigationController?.navigationBar.prefersLargeTitles = true
P3

self 키워드는 삭제해주세요.

2022-07-16 17:29 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/SettingViewController.swift
> +            settingTableView.heightAnchor.constraint(greaterThanOrEqualTo: view.heightAnchor)
P1

해당 constraint는 이렇게 작성한 이유가 있을까요? 
이럴 경우, tableView의 높이가 고정이 되지 않습니다. 디버깅을 해보면 오류를 알 수 있습니다.

<img width="578" alt="스크린샷 2022-07-17 오전 2 20 15" src="https://user-images.githubusercontent.com/56102421/179365416-2b978674-d9c2-4d8d-84f2-f069a8a20c10.png">

아래와 같이 변경해주세요.

```suggestion
            settingTableView.bottomAnchor.constraint(equalTo: view.bottomAnchor)
```

2022-07-16 17:29 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/SettingViewController.swift
> +        $0.contentInset = .init(top: 16, left: 0, bottom: 0, right: 0)
😶

2022-07-17 01:04 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/SettingViewController.swift
> +// MARK: - Protocol
오 감사합니다.
e38873c 에 반영했습니다.

2022-07-17 01:04 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/SettingViewController.swift
> +            self.present(eraseRecordAlert, animated: true)
무지성 따라쓰기의 폐해... e38873c 에 반영했습니다.

2022-07-17 01:05 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/SettingViewController.swift
> +        return cell
공식문서에 속았다...
버튼도 그렇고 웬만하면 configuration을 쓰는 걸로 바뀌었군요!
e38873c 에 반영했습니다.

2022-07-17 01:05 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/SettingViewController.swift
> +        settingTableView.delegate = self
웬만하면 초기화에 같이 넣어주자! 확인이요~
e38873c 에 반영했습니다.

2022-07-17 01:05 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/SettingViewController.swift
> +        self.navigationController?.navigationBar.prefersLargeTitles = true
e38873c 에 ㅂㅇ

2022-07-17 01:07 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/SettingViewController.swift
> +            settingTableView.heightAnchor.constraint(greaterThanOrEqualTo: view.heightAnchor)
아 이게 리스트가 혹시 화면을 넘어갈 때를 고려하여 작성한것인데, 얘는 스크롤뷰라 스크롤 가능한 영역만 지정해주면 되는 것이군요!(맞나요...?)
또 하나 배워갑니다!
e38873c 에 반영완료요~

2022-07-17 16:45 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/SettingViewController.swift
> +        return cell
컨텐츠가 화면에 한번에 보여지는 경우에는 상관없을 것 같아요. 만일, 화면에 10개의 데이터가 보여지는데 1만 개의 데이터를 표현해야할 경우, 재사용하게 된다면 메모리에는 10~20개의 셀만 가지게 되어서 메모리 효율을 좋게하는 용도입니다. SwiftUI의 `lazyVStack`의 동작원리를 잘 이해하지 못해서 같다다르다 판단이 힘듭니다만, 어떤 방식으로 동작하는지 아시나요?

2022-07-17 16:47 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/SettingViewController.swift
> +            settingTableView.heightAnchor.constraint(greaterThanOrEqualTo: view.heightAnchor)
tableView 내의 contentView가 스크롤이 되는 겁니다. tableView자체는 constraint를 확실하게 잡아주어야해요

2022-07-17 16:50 UTC, wody-d commented on Alarmi/Alarmi/Sources/ViewControllers/SettingViewController.swift
> +        $0.contentInset = .init(top: 16, left: 0, bottom: 0, right: 0)
아니요. 처음에 의도를 알 기 어려웠어서 이모지 작성해보았습니다. 깜박하고 안지웠네요. 😛

2022-07-17 16:50 UTC, wody-d approved these changes
🧨

2022-07-17 16:52 UTC, deslog commented on Alarmi/Alarmi/Sources/ViewControllers/SettingViewController.swift
> +// MARK: - Protocol
오 그렇군요! 배워갑니다,, 저도 protocol이라고 썼는데 ,, 당장 적용해야겠다

2022-07-18 00:22 UTC, Lim-YongKwan approved these changes
너무 수고하셨습니다!
코드 베이스라서 부분 부분 이해가 잘 안되는 부분이 있긴 했는데 전체적으로 깔끔하게 짜신것 같애요!
궁금했던 부분을 제외하고는 지적할 부분이 없어서 어프루브 날립니다!

2022-07-18 00:22 UTC, Lim-YongKwan commented on Alarmi/Alarmi/Sources/ViewControllers/SettingViewController.swift
> +        $0.contentOffset = .init(x: 0, y: -16)
이 부분이 궁금한데 좌표값으로 주면 기기들에 따라서 구현이 달라지지 않나요?
단순히 궁금해서 남깁니다!

2022-07-18 00:22 UTC, Lim-YongKwan commented on Alarmi/Alarmi/Sources/ViewControllers/SettingViewController.swift
> +
여기 중간에 줄을 띄우신 이유는 가독성 때문인가요?

2022-07-18 00:22 UTC, Lim-YongKwan commented on Alarmi/Alarmi/Sources/ViewControllers/SettingViewController.swift
> +        case 4:
코드가 잘 이해가 안되어서 남깁니다.
case 1이나 2나 3 부분은 굳이 구현이 안 되어도 되었나요?

2022-07-18 00:22 UTC, Lim-YongKwan commented on Alarmi/Alarmi/Sources/ViewControllers/SettingViewController.swift
> +import SwiftUI
SwiftUI를 참조해서 쓰신 부분이 너무 멋있습니다!
전 이런 방식은 생각하지도 못했는데 너무 멋있어요!

2022-07-18 00:27 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/SettingViewController.swift
> +        case 4:
case 0, 1, 2, 3은 나중에 각 화면으로 내비게이션하는 코드를 짜야 하는 부분입니다.
case가 비워져 있는 상태로 냅두면 오류가 나기 때문에 일단 작성하지 않고 TODO 주석으로 나중에 해야 한다고 작성해놓았습니다.

2022-07-18 00:29 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/SettingViewController.swift
> +        $0.contentOffset = .init(x: 0, y: -16)
좌표로 주는게 아니라 해당 콘텐츠를 y축으로 -16만큼 offset을 주겠다는 뜻이라 기기와는 상관이 없을 것입니다

2022-07-18 00:36 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/SettingViewController.swift
> +
네 이 부분은 content 변수를 생성하고, 그 속성을 변경했기 때문에 개행으로 구분해놨습니다.

2022-07-18 05:41 UTC, merged