[D0] 통화시간 화면 구성 #21
DeveloperAcademy-POSTECH/MC3-Team7-MoTe pull request #29
Opened 2022-07-18 04:22 UTC by wonny1012

## 이슈번호 
- #21 

## 작업사항
- CallTimeView부분을 작성 했습니다.
- 스토리 보드로 한 코드를 보니.. 못알아보겠군요 ㅜㅜ 
- 부모,자식 간 시간 조절을 가능하게 했습니다.
- 일단은 쿠퍼티노랑 한국기준으로 했어요!

- 우리하나 기준 오전, 오후로 기록이 되어 스케치와 다르게 디자인 됐습니다. 
- 쿠퍼티노는 TimeZone에 없어서 LA를 넣었습니다.
- 네비게이션 제목 설정이 잘 안되어서.. 일단 버튼으로 넣어놨는데.. 좀더 해봐야 할거같아요
- 버튼은 우디가 한거 쓸 예정입니다.

## 스크린샷

- UI 작업이었다면 개발 전과 후 화면을 캡처해서 올려주세요.

| 작업 전 | 작업 후 |
| ----- | ----- | 
<img width="250" alt="image" src="https://user-images.githubusercontent.com/102846055/179418903-3942048b-b8bc-491a-a0c6-7424c0d662cc.png">|![image width='250'](https://user-images.githubusercontent.com/102846055/179418884-356b4596-fbf3-47bc-981c-6987a774367e.png)|

## 검토할 사항
- [ ] 전부다..?
- [ ] 코드나 깃 잘 쓴게 맞는지 확인부탁합니다.

2022-07-18 08:06 UTC, Chaeho-Min requested changes
첫 UIKit 코딩 맞나요! 아주 잘해주셨습니다!

다만 오토레이아웃에 디자인 의도와 다른 부분들이 있어 수정이 필요합니다!
<img width="400" src="https://user-images.githubusercontent.com/75792767/179468718-90873dc7-06c2-4ec8-947b-4c7cff256129.png">

현재는 셀 안의 모든 요소들이 제각각의 뷰로 존재하는데, UIView나 UIStackView를 이용해서 위 그림의 주황색 부분을 하나의 덩어리로 묶고, centerXAnchor를 구속시켜주면 될 것 같습니다.

2022-07-18 08:06 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/SettingCallTimeViewController/CallTimeViewController.swift
> +        default : break
p3;

컨벤션에 따라 콜론은 왼쪽에 붙여쓰고,
위에 작성한 case 코드와의 통일성을 위해 break은 한 줄 띄워서 작성해주세요~

```suggestion
        default:
            break
```

2022-07-18 08:06 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/SettingCallTimeViewController/CallTimeViewController.swift
> +        default : break
여기도요~

2022-07-18 08:06 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/ViewControllers/SettingCallTimeViewController/CallTimeViewController.swift
> +        default : break
ㅇㄱㄷㅇ~

2022-07-18 08:23 UTC, wonny1012 commented on Alarmi/Alarmi.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 15.2;
지우면 될까요??

2022-07-18 08:27 UTC, Chaeho-Min commented on Alarmi/Alarmi.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 15.2;
제일 깔끔한 방법은 커밋 자체에서 이러한 변경사항이 있었던 기록을 없애는 것인데, 그 방법은 모르겠네요...

최소 버전은 15.5로 되돌리고, Team은 none으로 바꾸면 문제 없지 않을까요?

2022-07-18 13:18 UTC, Chaeho-Min approved these changes
스토리보드 코드리뷰 사항을 전부 깃헙에 적기는 힘들어서 일단 제가 수정해서 커밋 날렸습니다.
내일 수정사항에 대해 설명해드리겠습니다🚀🚀

2022-07-19 01:11 UTC, wody-d approved these changes
LGTM
컨플릿만 해결하고 머지해주세요

2022-07-19 01:14 UTC, merged