[Feat] 알림 매니저 1차 구현
DeveloperAcademy-POSTECH/MC3-Team7-MoTe pull request #59
Opened 2022-07-20 08:49 UTC by deslog

## 이슈번호 
- #48 

## 작업사항
- UserNotifications 를 사용해서 push 알림을 만들었습니다.
- TODO로 이후 작업해야할 사항을 표시해두었습니다.
- 지금 상황으로는 정해진 시간에 한번 뿌릴 수 있도록 작성할 수 있는데, push알림을 반복하기 위해서는 repeat 부분을 수정해야합니다. 일단 내일 있을 스프린트 리뷰와 빠른 스프린트 작업 진행을 위해 repeat부분은 제외한 채로 pr 날립니다. (그리즐리의 데이터 작업이 선행된 이후, 사용자가 설정한 '전화 주기'를 기준으로 repeat을 설정해야합니다.)

## 질문
- 혹시 push 알림 오는것에 대한 테스트는 어떻게 진행해야하나요? 저희는 사용자에게 입력받은 날짜 기준으로 알림을 주어야하기 때문에 주석처리되어있는 ```UNCalendarNotificationTrigger```를 사용해야하지만, push 알림이 정상적으로 뜨는지 확인하는 방법을 몰라서, 임시로 ```UNTimeIntervalNotificationTrigger```를 사용한 코드를 한 줄 더 추가해둔 상태입니다. 헤당 트리거는 'interval'를 초단위로 계산하여, 지금 작성된 코드 기준으로는 해당 페이지 런치 후 10초 뒤에 push알림이 뜨게끔 해둔 상황입니다.

## 스크린샷

| 사용자에게 권한 요청 | 알림이 뜨는 화면 |
| ----- | ----- | 
| ![alert](https://user-images.githubusercontent.com/96969693/179939381-48b2277b-c63c-437c-a256-9ddfae1efed9.gif)| ![푸시](https://user-images.githubusercontent.com/96969693/179939441-ddb35707-1c06-4577-bd53-6318bb728840.gif)|

## 검토할 사항
- [ ] 주석처리된 부분은 추후 필요한 코드이니 신경쓰지 말아주세요!
- [ ] 린트를 잘 지켜서 커밋하였는가
- [ ] sceneDelegate는 커밋되지 않았는가
- [ ] 컨벤션은 잘 지켜졌는가

2022-07-20 14:52 UTC, Chaeho-Min requested changes
알림은 이런 식으로 구현하는거군요. 잘 보고 갑니다!

다만 ViewController에 알림을 보내는 로직이 들어있는 것에 의문이 들어서 Request change 남깁니다!

2022-07-20 14:52 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/Register/RegisterNotifyViewController.swift
> +                    self.notificationCenter.add(request, withCompletionHandler: nil)
p2;

현재는 권한 alert에서 승인을 받을 경우 푸쉬 알림이 가게 만들었는데, 이 부분은 시연을 위한 것 같습니다.
실제 앱이 동작할 때는 alert에서 승인을 받을 경우 사용자가 알림 설정을 자유롭게 할 수 있게 하고(위 코드 상에서 아무 동작도 하지 않음), 승인 받지 못할 경우 알림 스위치를 OFF로 만든 후 사용자가 알림 설정을 건드리지 못하게 해야 할 것 같습니다(알림 권한 설정으로 가는 딥링크를 추가하는 방향도 고려).

아직 UserNotifications에 대해 몰라서 확답하기는 힘들지만, 실제 알림을 보내는 로직은 이 뷰컨트롤러가 아니라 다른 파일에서 돌아가야 할 것 같습니다.

따라서 이 부분은 브랜치를 따로 파서 시연용으로 남겨놓고(머지 X), PR로서 머지할 때는 없애야 하는 부분이라고 생각합니다.

2022-07-20 16:45 UTC, wody-d requested changes
아보 의견에 동의하여 이 브랜치를 이용하여 시연용으로 만들겠습니다.

2022-07-20 16:45 UTC, wody-d commented on Alarmi/Alarmi/Sources/Register/RegisterNotifyViewController.swift
> +                    self.notificationCenter.add(request, withCompletionHandler: nil)
전적으로 동의합니다.

2022-07-21 00:47 UTC, deslog commented on Alarmi/Alarmi/Sources/Register/RegisterNotifyViewController.swift
> +                    self.notificationCenter.add(request, withCompletionHandler: nil)
아하 제가 구현만 생각하고 만드느라 여기까지 생각을 하지 못했네요... ㅠㅠ 더 알아보고 파일분리해서 만들고 요청하신 알림설정까지 off 되게 만들겟습니다!

다만 지금 우디가 이 브랜치를 시연용으로 만들겠다고 했는데, 그럼 저는 브랜치를 새로 파서 작업하고 커밋하면 되는걸까요? ?

2022-07-21 03:23 UTC, Lim-YongKwan commented on Alarmi/Alarmi/Sources/Register/RegisterNotifyViewController.swift
> +                    print("Not Granted")
여기서 `Not Granted` print 문이 있는데 권한이 없는걸 확인하기 위한 작업인것 같은데 추후에도 필요할까요?
단순한 의문인데 궁금해서 물어봅니다!

2022-07-24 15:28 UTC, Gobans commented
안녕하세요 브라운 이리저리 탐방하다가 들렸는데 마침 알림 관련 PR이 있어서 들어와봤습니다
```swift
    func checkPendingNotificationRequests() {
        UNUserNotificationCenter.current().getPendingNotificationRequests { (notificationRequests) in
            if notificationRequests.isEmpty {
                print("Pending request 없음")
            } else{
                for notification: UNNotificationRequest in notificationRequests {
                    print("----------requests info------------")
                    print(notification.identifier)
                    print(notification.content.title)
                    print(notification.content.body)
                    print(notification.trigger ?? "No trigger")
                    print("-----------------------------------")
                }
            }
        }
    }
```
좀 시간이 지나서 해결했을지 모르지만, 현재 등록된 알림은 위와같은 메소드로 확인하실 수 있습니다.

2022-07-25 00:35 UTC, Lim-YongKwan approved these changes

2022-07-25 02:47 UTC, deslog commented
> 안녕하세요 브라운 이리저리 탐방하다가 들렸는데 마침 알림 관련 PR이 있어서 들어와봤습니다
> 
> ```swift
>     func checkPendingNotificationRequests() {
>         UNUserNotificationCenter.current().getPendingNotificationRequests { (notificationRequests) in
>             if notificationRequests.isEmpty {
>                 print("Pending request 없음")
>             } else{
>                 for notification: UNNotificationRequest in notificationRequests {
>                     print("----------requests info------------")
>                     print(notification.identifier)
>                     print(notification.content.title)
>                     print(notification.content.body)
>                     print(notification.trigger ?? "No trigger")
>                     print("-----------------------------------")
>                 }
>             }
>         }
>     }
> ```
> 
> 좀 시간이 지나서 해결했을지 모르지만, 현재 등록된 알림은 위와같은 메소드로 확인하실 수 있습니다.

오 고반 감사합니다!! 아직 해결하지 않았습니다... 허허... ^____^
다음 pr에 고반이 알려주신거 써볼게요! 감사합니다 😀

2022-07-25 02:47 UTC, closed without merging