[D0] 오늘 탭 UI 구현
DeveloperAcademy-POSTECH/MC3-Team7-MoTe pull request #97
Opened 2022-07-29 12:34 UTC by deslog

## 이슈번호 
#83 

## 작업사항
- 오늘 탭 UI를 구현했습니다.
- 실시간으로 돌아가는 시계는 구현 완료되었습니다.
  - 아래 ```setTimer()``` 코드가 1초마다 갱신되는 타이머 코드입니다.
```
private func setTimer() {
        Timer.scheduledTimer(timeInterval: 1, target: self, selector: #selector(self.currentTimeToKoreaTime(_:)), userInfo: nil, repeats: true)
    }
```
이렇게 1초마다 갱신되는 값을 아래 에서 처리해주었습니다.
```
@objc private func currentTimeToKoreaTime(_ sender: Timer) {
        let dateFormatter = DateFormatter()
        dateFormatter.locale = Locale(identifier: "Asia/Seoul")
        dateFormatter.timeZone = TimeZone(identifier: "Asia/Seoul")
        dateFormatter.dateFormat = "HH:mm"
        let currentLocationDate = Date()
        let koreaTime = dateFormatter.string(from: currentLocationDate)
        realTimeClockLabel.text = koreaTime
    }
```
  - 핸드폰 위치는 외국에 있다고 치고 구현
    - currentLocationDate (핸드폰위치) (Date) -> dateFormatter로 한국시간으로 변경 (String) -> 이걸 1초마다 계산해서 출력하는 과정
<br>

- 밑에 "D-day, 버튼" 있는 것은 두개가 같은 형태이기 때문에 ```TodayDdayView```  에 custom UIView를 만들었습니다.

## 스크린샷

| 아이폰13 | 아이폰8 | 아이폰13mini |
| ----- | ----- |  ----- |
|<img src="https://user-images.githubusercontent.com/96969693/181755520-a943e860-65f0-4654-9c78-2347c1218998.png" width="200"/>|<img src="https://user-images.githubusercontent.com/96969693/181755694-1176aecd-d5eb-4587-9310-6802c601c3bd.png" width="200"/>|<img src="https://user-images.githubusercontent.com/96969693/181756499-beb3630f-7fa9-412d-8f98-894d8b9e9605.png" width="200"/>|

## 다음에 할 일
 - [ ] 팬더 사진 줄이기 -> @wonny1012 가 레퍼런스 준다고함!
 - [ ] 팬더 위치 다시잡기 (지금 약간 위치들이 애매함..)
 - [ ] 시간에따라 사진 바뀌게 하기
 - [ ] D-day 데이터 연결
 - [ ] 버튼 로직 작업은 grizzly (내일 남은 태스크 받기로 함)

## 질문,,
 - 아직 머지가 되지 않은 파일이었어서 탭바가 없습니다. 탭바를 연결하면, 아이폰 8에는 판다가 설 자리가 없어져요 ㅠㅠ 이게맞나요..?
   - 제 생각은 고정되어있는 시계의 글자크기 108을 조금 줄어들어야 하지 않을까 싶습니다,,, 일단 탭바 올라오는거 보고 줄여볼게요.

## 검토할 사항
- [ ] Lint를 잘 지켰나요
- [ ] 코드 컨벤션은!?

2022-07-29 13:20 UTC, deslog commented
걱정하지마세요. 내일까지 무조건 완료 합니다.

![image](https://user-images.githubusercontent.com/96969693/181769095-75277852-b7d1-42ca-a42e-bc16ed3caa1a.png)

2022-07-30 06:30 UTC, Chaeho-Min requested changes
제가 생각없이 던져놓은 디자인을 구현하느라 정말 고생하셨습니다!😜
슬슬 어플이 완성되고 있는 것 같네요!
코멘트로 남긴 몇 가지 고려사항은 한 번 확인해보시고 반영해주시면 감사하겠습니다!

코드 말고도 몇 가지 남기고 싶은 말이 있어서 추가 코멘트 남깁니다.
1. TodayDdayView 파일이 Today 폴더 안에 같이 있으면 좋겠습니다. 이왕이면 'Supporting Views' 폴더를 Today 폴더 안에 만들고, 그 안에서 관리하면 다른 파일들의 폴더 구조와 유사해져서 좋을 것 같습니다.
2. 원래 일러스트는 svg 파일로 넣는 것을 생각하고 있었는데, 일단은 png 파일로 진행해도 괜찮을 것 같습니다. svg 파일을 넣으면 느려지는 경우를 종종 봐서 후순위 고려사항으로 둡시다!

2022-07-30 06:30 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/MainTab/Today/TodayViewController.swift
> +    }(UILabel())
p1;

<img width="150" src="https://user-images.githubusercontent.com/75792767/181877031-79f1f906-70a2-49c8-9de7-068bb23a0984.gif">

realTimeClockLabel에 기본값이 할당되어있지 않아 앱이 실행되고 나서 1초가 지날때까지 라벨이 시계 없이 나타나게 됩니다. 기본값을 추가해주세요.
```suggestion
    private lazy var realTimeClockLabel: UILabel = {
        $0.translatesAutoresizingMaskIntoConstraints = false
        $0.adjustsFontSizeToFitWidth = true
        $0.textAlignment = .center
        $0.text = dateFormatter.string(from: Date())
        $0.font = UIFont.systemFont(ofSize: 108, weight: .black)
        return $0
    }(UILabel())
```

2022-07-30 06:30 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/MainTab/Today/TodayViewController.swift
> +        fromPurposeDDayView.set(state: .init(buttonName: "미룰거예요", descriptionLabelName: "목표일로부터", dDayLabel: "D+2"))
p3;

둘 다 초기화 부분에 추가할 수 있을 것 같습니다!
```swift
private lazy var lastCallDDayView: TodayDdayView = {
    $0.translatesAutoresizingMaskIntoConstraints = false
    $0.set(state: .init(buttonName: "전화했어요", descriptionLabelName: "마지막 전화", dDayLabel: "D+9"))
    return $0
}(TodayDdayView())
```

2022-07-30 06:30 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/MainTab/Today/TodayViewController.swift
> +    }
p4;

제가 생명주기를 잘 모르긴 한데 setTimer가 뷰가 나타나기 전에 호출되어야 할 필요가 있나요?
viewDidLoad에 있어도 문제가 없을 것 같은데 어디에 있는게 더 좋은지는 몰라서 코멘트 남깁니다!

2022-07-30 06:30 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/MainTab/Today/TodayViewController.swift
> +        dateFormatter.dateFormat = "HH:mm"
p2;

dateFormatter를 1초마다 생성하지 않고 클래스 초기화 때 한 번만 생성한 후 사용하는게 더 좋을 것 같습니다!

```swift
private let dateFormatter: DateFormatter = {
    $0.locale = Locale(identifier: "Asia/Seoul")
    $0.timeZone = TimeZone(identifier: "Asia/Seoul")
    $0.dateFormat = "HH:mm"
    return $0
}(DateFormatter())
```

2022-07-30 06:30 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/Register/Supporting Views/TodayDdayView.swift
> +        $0.configuration?.contentInsets = NSDirectionalEdgeInsets(top: 11, leading: 15, bottom: 15, trailing: 11)
p1;

inset을 잘못 준 것 같습니다! 지금 top, trailing이 같고 leading, bottom이 같네요😝

```suggestion
        $0.configuration?.contentInsets = NSDirectionalEdgeInsets(top: 11, leading: 16, bottom: 11, trailing: 16)
```

2022-07-30 06:30 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/Register/Supporting Views/TodayDdayView.swift
> +        delegate?.presentCallDelayViewController()
p1;

현재 TodayDdayView에 delegate를 할당해주지 않아 버튼을 누를시 어플이 종료되는데, 아직 구현을 안 한 것일까요?

2022-07-30 06:40 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/MainTab/Today/TodayViewController.swift
> +        $0.setDynamicFont(for: .body, weight: .bold)
이건 제가 스케치상에 잘못 올렸네요...ㅎㅎ
여기도 semibold입니다.🙇‍♂️

2022-07-30 06:55 UTC, deslog commented on Alarmi/Alarmi/Sources/MainTab/Today/TodayViewController.swift
> +    }(UILabel())
헐 이게 이런 원인이었군요, 안그래도 이부분에 대해서 따로 올려야겠다고생각했는데, 감사합니다! 수정해서 커밋날릴게요

2022-07-30 09:24 UTC, deslog commented on Alarmi/Alarmi/Sources/MainTab/Today/TodayViewController.swift
> +        dateFormatter.dateFormat = "HH:mm"
[4beeecf](https://github.com/DeveloperAcademy-POSTECH/MC3-Team7-MoTe/pull/97/commits/4beeecfd71c85104fa8bd37912a97c7c630c5d4f)
네 맞네요...!!!

2022-07-30 09:25 UTC, deslog commented on Alarmi/Alarmi/Sources/MainTab/Today/TodayViewController.swift
> +    }(UILabel())
감사합니다 수정완료했습니당 [4beeecf](https://github.com/DeveloperAcademy-POSTECH/MC3-Team7-MoTe/pull/97/commits/4beeecfd71c85104fa8bd37912a97c7c630c5d4f)

2022-07-30 09:28 UTC, deslog commented on Alarmi/Alarmi/Sources/MainTab/Today/TodayViewController.swift
> +        fromPurposeDDayView.set(state: .init(buttonName: "미룰거예요", descriptionLabelName: "목표일로부터", dDayLabel: "D+2"))
아,, 이런거까지 고려를 못했네용,, 이렇게 바꾸니 훨씬깔끔하고 직관적입니다! 감사합니다 [03244d0](https://github.com/DeveloperAcademy-POSTECH/MC3-Team7-MoTe/pull/97/commits/03244d0bf5b8af35c071727e44f553d76904640f)

2022-07-30 09:30 UTC, deslog commented on Alarmi/Alarmi/Sources/Register/Supporting Views/TodayDdayView.swift
> +        $0.configuration?.contentInsets = NSDirectionalEdgeInsets(top: 11, leading: 15, bottom: 15, trailing: 11)
앗 캐치해주셔서 감사합니당! 꼼꼼아보 👍[407c187](https://github.com/DeveloperAcademy-POSTECH/MC3-Team7-MoTe/pull/97/commits/407c187926ec6599266fddad41d867a1fb0a5c34)

2022-07-30 09:36 UTC, deslog commented on Alarmi/Alarmi/Sources/MainTab/Today/TodayViewController.swift
> +        $0.setDynamicFont(for: .body, weight: .bold)
오호 수정완료! [777f859](https://github.com/DeveloperAcademy-POSTECH/MC3-Team7-MoTe/pull/100/commits/777f8590f32223304331a4d958af646bef57db81)

2022-07-30 09:48 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/MainTab/Today/TodayViewController.swift
> +        dateFormatter.dateFormat = "HH:mm"
함수 안에 아직 두 줄이 남아있어요...!!

```swift
dateFormatter.timeZone = TimeZone(identifier: "Asia/Seoul")
dateFormatter.dateFormat = "HH:mm"
```

2022-07-30 09:49 UTC, deslog commented on Alarmi/Alarmi/Sources/MainTab/Today/TodayViewController.swift
> +    }
ViewDidLoad와 ViewWillAppear은 뷰의 생성시점과 보여주는 시점을 분리했다는 것에서 차이가 있습니다. 

ViewDidLoad는 view object가 생성된 후 발생하는 이벤트이고, viewWillAppear은 view가 안보이다가 다시 보이게 됐을 경우에 발생되는 이벤트입니다. 그래서 A->B->C 순서대로 네비게이션이 발생할때, A->B->C 로 갈때는 ViewDidLoad, ViewWillAppear 모두 생하지만, C에서 돌아올때는 ViewWillAppear만 발생한다고 하는데,,, 
처음에는 당엲연히 그럼 ViewWillAppear에 넣어야지!! 생각했는데

어차피 한번 로드된 이후에 타이머가 계속 돌고있으면 ViewDidLoad에 넣어도 될것같다는 생각이 지금 막 드는데요...!.!?!?!... 

다시 생각해 보니까 ViewDidLoad에 넣는게 맞을것같아요.
ViewWillAppear은 , 어디에 들어갔다가 다시 돌아올때 발생하는 이벤트에 한해서 넣어주는게 맞는것같네요!! ㅎㅎㅎㅎ

2022-07-30 09:52 UTC, Chaeho-Min commented on Alarmi/Alarmi/Sources/MainTab/Today/TodayViewController.swift
> +    }
오호 viewWillAppear는 내비게이션 이동이나 어플에서 홈 화면으로 갔다가 다시 돌아오는 경우에 실행되길 원하는 애들을 넣어주는 생명주기군요! 👍

2022-07-30 09:52 UTC, deslog commented on Alarmi/Alarmi/Sources/MainTab/Today/TodayViewController.swift
> +    }
수정완료! [251171a](https://github.com/DeveloperAcademy-POSTECH/MC3-Team7-MoTe/pull/100/commits/251171ab4c4c67f9cecf988dcc98498acb66c11f)

2022-07-30 09:57 UTC, deslog commented on Alarmi/Alarmi/Sources/MainTab/Today/TodayViewController.swift
> +        dateFormatter.dateFormat = "HH:mm"
아아앗.. [0b052a2](https://github.com/DeveloperAcademy-POSTECH/MC3-Team7-MoTe/pull/97/commits/0b052a255fd47b6ffa2c5cb05e77968f0ecabf34)

2022-07-30 10:51 UTC, wody-d approved these changes
아보가 리뷰를 잘해주셨네요 :) 뷰 구현해주시느라 수고 많으셨습니다.

아직 ViewModel에 구현이 안되어있어보입니다. 다음 작업에 마무리해주시면 로직을 분리해주시면 좋아보여요.
그리고 이번에 작업하신 TodayDdayView 같은 경우 내부 구조체의 네이밍이 State보다 Type이 낫지 않을까요? State는 상태를 의미하는데 디데이 컴포넌트 같은 경우, 하나의 상태만 가지고 있다고 판단되어서요. 같이 이야기 나눠보고 개선했으면 좋겠네요.

현재 버그에 대해선 아보가 request change하였으니 저는 어푸릅하겠습니다. 해결해주시고 머지해주세요 :)

2022-07-30 10:51 UTC, wody-d commented on Alarmi/Alarmi/Sources/MainTab/Today/TodayViewController.swift
> +        $0.image = UIImage(named: "call")
P1) 더미같은 경우 viewModel에서 넘겨주도록 합시다

2022-07-30 10:51 UTC, wody-d commented on Alarmi/Alarmi/Sources/MainTab/Today/TodayViewController.swift
> +        Timer.scheduledTimer(timeInterval: 1, target: self, selector: #selector(self.currentTimeToKoreaTime(_:)), userInfo: nil, repeats: true)
저희 서비스의 특징은 한국시간의 특정 시각에 어떤 처리를 해주어야 합니다. 어떤 처리는 아래와 같습니다.
1. 오늘 탭의 한국 시계 업데이트
2. 앱의 다크모드/라이트모드 체인지
3. 오늘 탭의 판다 업데이트

이 3가지 처리는 전부 다르게 하는 것이 아니라 같은 처리를 해야 합니다. 다른 처리를 하게 될 경우, 다르게 동작할 수 있는 상황이 생길 뿐더러, 다른 어떤 사이드 이펙트가 생길지 모릅니다. 만일 오늘탭의 타이머가 이상이 생겨 멈추게될경우, 시간은 업데이트가 되지않는데, 앱의 색은 변하게 됩니다. 혹은, 한국 시간과 이미지가 매치가 되지 않는 상황이 발생할 수 있습니다. 

따라서, 이후에 snyc작업이 필요해보입니다.

2022-07-31 01:45 UTC, deslog commented on Alarmi/Alarmi/Sources/MainTab/Today/TodayViewController.swift
> +        Timer.scheduledTimer(timeInterval: 1, target: self, selector: #selector(self.currentTimeToKoreaTime(_:)), userInfo: nil, repeats: true)
네! !!

2022-07-31 04:25 UTC, deslog commented
카톡에서 이야기 나온대로 일단 머지 하겠습니다,,!

2022-07-31 04:25 UTC, merged